services:
    db:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: root1234
            MYSQL_DATABASE: book_rental_db
        volumes:
            -   db_data:/var/lib/mysql
        ports:
            -   "3306:3306"

    web:
        build: .
        ports:
            -   "8000:8000"
        depends_on:
            -   db
        environment:
            DB_HOST: db

volumes:
    db_data:
